### ISSUE TITLE
hard to find editor window when covered

### ISSUE THREAD

**Issue by philburk** [philburk/hmsl#15]
TO REPRODUCE:
launch HMSL
enter: SHEP
See shape editor window
Bring Browser or other program to the front.
Click terminal icon in Dock to bring it to the front.

EXPECT:
Shape editor window should also come to front.

ACTUAL:
Shape editor window still buried under browser.

Also if I go to the mode that shows all windows then click on SHEP it does not come to front.  This makes it hard for a user to return to the editor.

This may be because SHEP is in a window off a shell command and not a real app.  This may be hard to fix.

**Comment by andrewcsmith** [comment]
This should be fixed now with the latest push. Let me know if you got the .app bundle and if it all works we can close this.

**Comment by philburk** [comment]
I can find the window now because it has an icon in the dock.
