### ISSUE TITLE
Crash when setting font size before opening window

### ISSUE THREAD

**Issue by andrewcsmith** [philburk/hmsl#16]
Probably because the NSFont hasn't been initialized yet.

**Comment by philburk** [comment]
I think because gr.font! calls gr.setport, which passes a null down to native code. Maybe it should not call native with a NULL, or native could protect itself.

**Comment by andrewcsmith** [comment]
It's actually in the osx obj-c layer. It tries to copy info from the "current font" to change the font size, but the current font isn't actually initialized until a window is opened. I'll move the current font initialization to hostInit() and it should be fine.

**Comment by andrewcsmith** [comment]
Fixed.
