### ISSUE TITLE
HMSL cannot read the dictionary file on recent Mac OS

### ISSUE THREAD

**Issue by philburk** [philburk/hmsl#164]
There is apparently a security restriction that prevents reading files outside the package.

Solutions may involve:

* moving the .dic file into the package
* building a pre-compiled header with SAVE-DICD
* adding permissions to HMSL

Can HMSL load .fth files?

**Comment by philburk** [comment]
If I build HMSL then I can run it without error.
If I put together a release folder then I can run the JuceHMSL.app without error.
But if I download the ZIP release and open it with the Control key then 
it runs but then crashes. It is not obvious that the crash is caused by trying to read the file. It may not be.

**Comment by wwerkk** [comment]
would the following error on launch be related?
```
/private/var/folders/kt/3yzrdbd5481fc1w4yd4phIwm0000gn/T/AppTranslocation/8D78D193-1089-4544-AF9C-233B3CFE5624/d
PForth V28-LE/64, built Mar 6 2022 17:47:48
Error in pfloadDictionary - could not open file
pfDoForth: Error occured.
```

**Comment by philburk** [comment]
This was solved by giving HMSL sandbox permission to read/write files in ~/Music/HMSL folder.
