### ISSUE TITLE
Window title bar does not show full title

### ISSUE THREAD

**Issue by andrewcsmith** [philburk/hmsl#17]
Should say "HMSL v5.0"
![screenshot 2015-08-26 09 45 01](https://cloud.githubusercontent.com/assets/378677/9499928/2f52261c-4bd7-11e5-8734-4b13d9072009.png)

**Comment by andrewcsmith** [comment]
Doesn't seem to happen in 10.9

**Comment by andrewcsmith** [comment]
Second opening of window also is 10.10-specific

**Comment by philburk** [comment]
Now on El Capitan the title bar is completely empty. No close icons.
<img width="692" alt="shep_no_title_icons" src="https://cloud.githubusercontent.com/assets/5175913/11068160/e82aa612-8784-11e5-80ea-ae7d510d2fd5.png">

**Comment by andrewcsmith** [comment]
Yep, for me too. Must be a 10.9 to 10.10 thing.

**Comment by andrewcsmith** [comment]
Fixed in #49, and although that unfortunately creates new problems I think this at least gets the app package into a place where people can start alpha testing it.
