### ISSUE TITLE
Install instructions don't mention Mac System Settings interaction

### ISSUE THREAD

**Issue by darrengit** [philburk/hmsl#181]
When trying to launch the latest app version on macOS 15, Control-right-click didn't work.  Annoyingly, there's no prompt from the OS that after the app launch fails, you can open System Settings -> Privacy & Security, scroll all the way to the bottom and choose "Launch Anyway" when an app is blocked.

**Comment by philburk** [comment]
@darrengit - Thanks for the feedback. I updated [install.md](https://github.com/philburk/hmsl/blob/master/docs/install.md).
