### ISSUE TITLE
8 gr.color! crashes

### ISSUE THREAD

**Issue by philburk** [philburk/hmsl#23]
Enter:
    hmsl.open
    3 gr.color!   \ OK
    8 gr.color!

Get:
 /Users/phil/Work/HMSL/hmsl/hmsl.app/Contents/MacOS/start_hmsl.sh: line 5:  8055 Bus error: 10           ../MacOS/hmsl
logout

This was found by entering:
    include /Users/phil/Work/HMSL/hmsl/fth/test_graphics.fth 
    tgr.init
    random.rects

**Comment by andrewcsmith** [comment]
Note to self—double-check the indexing of the color table.

**Comment by philburk** [comment]
In hmsl.h I see:

static const double hmslYellow[4] = {1.0, 1.0, 1.0, 1.0}; // now black so that xor works
static const double* hmslColors[8] = {

Two things, yellow is not yellow nor black. Also colors limited to 8. I think we had 16 colors before. 

I see that you matched the Windows pHMSL color palette. But it may not be correct. Here is a palette according to Wikipedia:
https://en.wikipedia.org/wiki/List_of_software_palettes#Apple_Macintosh_default_16-color_palette

But it seems odd that black is 15 and not 1.

Maybe add 8 more and then clip the index between 0 and 15.

Windows and OSX should match. I wish we had a running system that we could check. Maybe I will post some code on the HMSL list that displays colored boxes. Then someone could run it on an old Mac.

**Comment by andrewcsmith** [comment]
Here's a quick (conservative) fix for the `8 gr.color!` crash: 3c79fffc5e5929bb86469474f65238b099369333

Since XOR doesn't work in Quartz drawing, the color palette is somewhat hobbled. If you want to see how that looks, I created a separate branch [color-revision](https://github.com/philburk/hmsl/tree/color-revision) to track that.

**Comment by andrewcsmith** [comment]
The colors outlined in the windows version maintain the same ordering as the `[fth/graphics.fth:31](https://github.com/philburk/hmsl/blob/master/hmsl/fth/graphics.fth#L31-L39)`

**Comment by andrewcsmith** [comment]
This now at least matches the previous colors closely. Perhaps the current implementation works for now, and we can break it into a feature allowing users to customize the rgba values of the drawing colors? That will let people simulate old pieces / machines as needed.

**Comment by philburk** [comment]
The 8 gr.color! crash is fixed so closing.
