### ISSUE TITLE
warning immediately from SHEP

### ISSUE THREAD

**Issue by philburk** [philburk/hmsl#30]
After installing El Capitan on my Mac, I am now getting a warning immediately after entering SHEP. The shape editor runs OK after this.

shep Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const: conn 0x9233 token 0x1ffffffffffe85
Oct 28 08:57:17  hmsl[1281] <Warning>: Backtrace (at 16175.7):
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  0   CoreGraphics                        0x9821bb91 CGSDisableUpdateToken + 228
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  1   AppKit                              0x9a241a51 **_disable_updates_sync_block_invoke_2 + 19
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  2   libdispatch.dylib                   0x926de7e7 _dispatch_client_callout + 50
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  3   libdispatch.dylib                   0x926e00b8 _dispatch_barrier_sync_f_invoke + 61
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  4   libdispatch.dylib                   0x926e0074 dispatch_barrier_sync_f + 98
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  5   libdispatch.dylib                   0x926ea6cb dispatch_barrier_sync + 54
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  6   AppKit                              0x9a24193a NSCGSDisableUpdates + 1302
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  7   AppKit                              0x9a24134f NSCGSTransactionRunPreCommitActionsForOrder_ + 159
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  8   AppKit                              0x9a24129e NSCGSTransactionRunPreCommitActions_ + 26
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  9   AppKit                              0x9a222467 -[_NSCGSTransaction addActionWithOrder:usingBlock:] + 236
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  10  AppKit                              0x9a222361 NSCGSTransactionAddAction + 115
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  11  AppKit                              0x9a221d41 NSCGSWindowBackingStoreMark_ + 266
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  12  AppKit                              0x9a221c2d -[_NSCGSWindowBackingStore setAttached:] + 43
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  13  AppKit                              0x9a221951 -[NSCGSWindow(NSCGSWindowBackingStore) setHasBackingStore:] + 89
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  14  AppKit                              0x9a2ff8d0 _NSCreateWindowWithOpaqueShape2 + 120
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  15  AppKit                              0x9a2fe343 -[NSWindow _commonAwake] + 2259
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  16  AppKit                              0x9a2fd9e0 -[NSWindow _makeKeyRegardlessOfVisibility] + 104
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  17  AppKit                              0x9a2fd8fa -[NSWindow makeKeyAndOrderFront:] + 35
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  18  hmsl                                0x00019f75 +[HMSLWindow hmslWindowWithTitle:frame:] + 501
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  19  hmsl                                0x00018eb6 hmslOpenWindow + 310
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  20  hmsl                                0x00017ab8 hostOpenWindow + 168
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  21  hmsl                                0x0000fd91 CallUserFunction + 145
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  22  hmsl                                0x00010807 pfCatch + 1687
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  23  hmsl                                0x0000f1d4 FindAndCompile + 132
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  24  hmsl                                0x0000f113 ffInterpret + 259
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  25  hmsl                                0x0000f5dc ffOuterInterpreterLoop + 44
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  26  hmsl                                0x00014558 pfQuit + 40
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  27  hmsl                                0x00014b81 pfDoForth + 785
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  28  hmsl                                0x0001a65a -[HMSLRunner goForth] + 74
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  29  Foundation                          0x94dc9987 -[NSThread main] + 45
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  30  Foundation                          0x94dc9712 __NSThread__start** + 1550
Oct 28 08:57:17  hmsl[1281] <Warning>: void CGSUpdateManager::log() const:  31  libsystem_pthread.dylib             0x94c94794 _pthread_body + 138

**Comment by andrewcsmith** [comment]
I haven't been able to reproduce this one. Let me know if it happens with the latest (0.3.4) build.

**Comment by philburk** [comment]
I ran app from your email. It still says V0.3.3 when I click on it in Finder.
I don't get the warning on HMSL.INIT. But I still see the warning in SHEP.

I got this message but it only appeared after I drew in he shape.

shep Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const: conn 0x272df token 0x1ffffffffffe85
Nov  9 09:39:21  hmsl[15759] <Warning>: Backtrace (at 493060):
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  0   CoreGraphics                        0x9821bb91 CGSDisableUpdateToken + 228
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  1   AppKit                              0x9a241a51 ___disable_updates_sync_block_invoke_2 + 19
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  2   libdispatch.dylib                   0x926de7e7 _dispatch_client_callout + 50
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  3   libdispatch.dylib                   0x926e00b8 _dispatch_barrier_sync_f_invoke + 61
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  4   libdispatch.dylib                   0x926e0074 dispatch_barrier_sync_f + 98
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  5   libdispatch.dylib                   0x926ea6cb dispatch_barrier_sync + 54
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  6   AppKit                              0x9a24193a NSCGSDisableUpdates + 1302
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  7   AppKit                              0x9a24134f NSCGSTransactionRunPreCommitActionsForOrder_ + 159
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  8   AppKit                              0x9a24129e NSCGSTransactionRunPreCommitActions_ + 26
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  9   AppKit                              0x9a222467 -[_NSCGSTransaction addActionWithOrder:usingBlock:] + 236
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  10  AppKit                              0x9a222361 NSCGSTransactionAddAction + 115
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  11  AppKit                              0x9a221d41 NSCGSWindowBackingStoreMark_ + 266
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  12  AppKit                              0x9a221c2d -[_NSCGSWindowBackingStore setAttached:] + 43
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  13  AppKit                              0x9a221951 -[NSCGSWindow(NSCGSWindowBackingStore) setHasBackingStore:] + 89
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  14  AppKit                              0x9a2ff8d0 _NSCreateWindowWithOpaqueShape2 + 120
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  15  AppKit                              0x9a2fe343 -[NSWindow _commonAwake] + 2259
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  16  AppKit                              0x9a2fd9e0 -[NSWindow _makeKeyRegardlessOfVisibility] + 104
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  17  AppKit                              0x9a2fd8fa -[NSWindow makeKeyAndOrderFront:] + 35
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  18  hmsl                                0x0006c715 +[HMSLWindow hmslWindowWithTitle:frame:] + 501
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  19  hmsl                                0x0006b616 hmslOpenWindow + 310
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  20  hmsl                                0x0006a238 hostOpenWindow + 168
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  21  hmsl                                0x00062511 CallUserFunction + 145
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  22  hmsl                                0x00062f87 pfCatch + 1687
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  23  hmsl                                0x00061954 FindAndCompile + 132
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  24  hmsl                                0x00061893 ffInterpret + 259
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  25  hmsl                                0x00061d5c ffOuterInterpreterLoop + 44
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  26  hmsl                                0x00066cd8 pfQuit + 40
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  27  hmsl                                0x00067301 pfDoForth + 785
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  28  hmsl                                0x0006cf58 -[HMSLRunner goForth:] + 424
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  29  Foundation                          0x94dc9987 -[NSThread main] + 45
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  30  Foundation                          0x94dc9712 __NSThread__start__ + 1550
Nov  9 09:39:21  hmsl[15759] <Warning>: void CGSUpdateManager::log() const:  31  libsystem_pthread.dylib             0x94c94794 _pthread_body + 138

**Comment by andrewcsmith** [comment]
Okay, thanks. Took me some clicking but I reproduced it. I'll try and set some breakpoints and see what's up.

**Comment by andrewcsmith** [comment]
Still an issue? I'm thinking this might be fixed by today's commit as well, but perhaps that's wishful thinking.

**Comment by philburk** [comment]
Sadly, this is still happening with the latest build. I can reproduce it reliably if I just enter SHEP and wait 15 seconds.

**Comment by rsnewcomb** [comment]
Hello Phil and Andrew - I have just begun working with your pforth/phmsl/OSX port.  I reported to Phil that the HMSL binary he sent me a week ago displayed errors/warnings when SHEP is run (under OSX 10.8.5).  As of yesterday, I have upgraded to El Capitan (10.11.3) on a 2012 MBP (16GB RAM).  The same binary now gives me basically the same warnings as Phil notes in this ticket (excuse the large paste; please let me know if you prefer errors or logs to be attached as text files or pasted into these issues):

HMSL Initialized and Ready!
SHEP 2016-02-28 14:49:08.621 hmsl[1355:48869] NSWindow warning: adding an unknown subview: <NSView: 0x7c8552a0>. Break on NSLog to debug.
2016-02-28 14:49:08.695 hmsl[1355:48869] Call stack:
(
	0   AppKit                              0x96c7b77b -[NSThemeFrame addSubview:] + 108
	1   hmsl                                0x000fe02b +[HMSLWindow hmslWindowWithTitle:frame:] + 283
	2   hmsl                                0x000fd116 hmslOpenWindow + 310
	3   hmsl                                0x000fbb78 hostOpenWindow + 168
	4   hmsl                                0x000f2bc1 CallUserFunction + 145
	5   hmsl                                0x000f36bd pfCatch + 1821
	6   hmsl                                0x000f1f94 FindAndCompile + 132
	7   hmsl                                0x000f1ed3 ffInterpret + 259
	8   hmsl                                0x000f240c ffOuterInterpreterLoop + 44
	9   hmsl                                0x000f82d8 pfQuit + 40
	10  hmsl                                0x000f8911 pfDoForth + 785
	11  hmsl                                0x000fec28 -[HMSLRunner goForth:] + 424
	12  Foundation                          0x9b2b933b -[NSThread main] + 45
	13  Foundation                          0x9b4792a6 __NSThread__start__ + 1550
	14  libsystem_pthread.dylib             0x9d3aea26 _pthread_body + 138
	15  libsystem_pthread.dylib             0x9d3ae99c _pthread_body + 0
	16  libsystem_pthread.dylib             0x9d3abf96 thread_start + 34
)
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const: conn 0x9ff3 token 0x1ffffffffffe85
Feb 28 14:49:23  hmsl[1355] <Warning>: Backtrace (at 6820.57):
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  0   CoreGraphics                        0x93156d85 CGSDisableUpdateToken + 228
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  1   AppKit                              0x97660ff1 ___disable_updates_sync_block_invoke_2 + 19
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  2   libdispatch.dylib                   0x9e4d7763 _dispatch_client_callout + 50
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  3   libdispatch.dylib                   0x9e4d9034 _dispatch_barrier_sync_f_invoke + 61
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  4   libdispatch.dylib                   0x9e4d8ff0 dispatch_barrier_sync_f + 98
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  5   libdispatch.dylib                   0x9e4e3647 dispatch_barrier_sync + 54
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  6   AppKit                              0x9765fefd NSCGSDisableUpdates + 229
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  7   AppKit                              0x976611aa NSCGSTransactionRunPreCommitActionsForOrder_ + 159
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  8   AppKit                              0x9766012f NSCGSTransactionRunPreCommitActions_ + 26
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  9   AppKit                              0x976603ce -[_NSCGSTransaction addActionWithOrder:usingBlock:] + 237
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  10  AppKit                              0x97660b65 NSCGSTransactionAddAction + 115
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  11  AppKit                              0x9765d732 NSCGSWindowBackingStoreMark_ + 266
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  12  AppKit                              0x9765d61e -[_NSCGSWindowBackingStore setAttached:] + 43
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  13  AppKit                              0x9765ee8f -[NSCGSWindow(NSCGSWindowBackingStore) setHasBackingStore:] + 89
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  14  AppKit                              0x96cdd39c _NSCreateWindowWithOpaqueShape2 + 120
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  15  AppKit                              0x96cdbb2b -[NSWindow _commonAwake] + 2259
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  16  AppKit                              0x96d663b4 -[NSWindow _makeKeyRegardlessOfVisibility] + 104
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  17  AppKit                              0x974f96d2 __33-[NSWindow makeKeyAndOrderFront:]_block_invoke + 36
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  18  AppKit                              0x97539de1 NSPerformVisuallyAtomicChange + 212
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  19  AppKit                              0x96d66267 -[NSWindow makeKeyAndOrderFront:] + 84
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  20  hmsl                                0x000fe139 +[HMSLWindow hmslWindowWithTitle:frame:] + 553
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  21  hmsl                                0x000fd116 hmslOpenWindow + 310
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  22  hmsl                                0x000fbb78 hostOpenWindow + 168
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  23  hmsl                                0x000f2bc1 CallUserFunction + 145
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  24  hmsl                                0x000f36bd pfCatch + 1821
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  25  hmsl                                0x000f1f94 FindAndCompile + 132
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  26  hmsl                                0x000f1ed3 ffInterpret + 259
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  27  hmsl                                0x000f240c ffOuterInterpreterLoop + 44
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  28  hmsl                                0x000f82d8 pfQuit + 40
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  29  hmsl                                0x000f8911 pfDoForth + 785
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  30  hmsl                                0x000fec28 -[HMSLRunner goForth:] + 424
Feb 28 14:49:23  hmsl[1355] <Warning>: void CGSUpdateManager::log() const:  31  Foundation

**Comment by philburk** [comment]
SHEP now fails on Mac with:
shep 2019-04-28 11:06:27.065 hmsl[87378:6506990] WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (
	0   AppKit                              0x915228bd -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 354
	1   AppKit                              0x915b3bf2 -[NSWindow _enablePosting] + 119
	2   AppKit                              0x915200a2 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1684
	3   AppKit                              0x9151fa07 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 46
	4   hmsl                                0x00004fa2 +[HMSLWindow hmslWindowWithTitle:frame:] + 130
	5   hmsl                                0x000044d6 hmslOpenWindow + 310
	6   hmsl                                0x00002cae hostOpenWindow + 142
	7   hmsl                                0x0000983e CallUserFunction + 142
	8   hmsl                                0x0000a235 pfCatch + 1653
	9   hmsl                                0x000123bb FindAndCompile + 123
	10  hmsl                                0x00012302 ffInterpret + 242
	11  hmsl                                0x000127e9 ffOuterInterpreterLoop + 41
	12  hmsl                                0x000081f5 pfQuit + 37
	13  hmsl                                0x000087bb pfDoForth + 747
	14  hmsl                                0x00005f28 -[HMSLRunner goForth:] + 424
	15  Foundation                          0x95110ce6 -[NSThread main] + 39
	16  Foundation                          0x95110b8f __NSThread__start__ + 1220
	17  libsystem_pthread.dylib             0xa7d985f8 _pthread_body + 137
	18  libsystem_pthread.dylib             0xa7d9b7f7 _pthread_start + 78
	19  libsystem_pthread.dylib             0xa7d977ce thread_start + 34
)
2019-04-28 11:06:27.067 hmsl[87378:6506990] NSWindow warning: adding an unknown subview: <NSView: 0x52bdc0>. Break on NSLog to debug.
2019-04-28 11:06:27.067 hmsl[87378:6506990] Call stack:
(
	0   AppKit                              0x91538d5c -[NSThemeFrame addSubview:] + 108
	1   hmsl                                0x0000503b +[HMSLWindow hmslWindowWithTitle:frame:] + 283
	2   hmsl                                0x000044d6 hmslOpenWindow + 310
	3   hmsl                                0x00002cae hostOpenWindow + 142
	4   hmsl                                0x0000983e CallUserFunction + 142
	5   hmsl                                0x0000a235 pfCatch + 1653
	6   hmsl                                0x000123bb FindAndCompile + 123
	7   hmsl                                0x00012302 ffInterpret + 242
	8   hmsl                                0x000127e9 ffOuterInterpreterLoop + 41
	9   hmsl                                0x000081f5 pfQuit + 37
	10  hmsl                                0x000087bb pfDoForth + 747
	11  hmsl                                0x00005f28 -[HMSLRunner goForth:] + 424
	12  Foundation                          0x95110ce6 -[NSThread main] + 39
	13  Foundation                          0x95110b8f __NSThread__start__ + 1220
	14  libsystem_pthread.dylib             0xa7d985f8 _pthread_body + 137
	15  libsystem_pthread.dylib             0xa7d9b7f7 _pthread_start + 78
	16  libsystem_pthread.dylib             0xa7d977ce thread_start + 34

**Comment by philburk** [comment]
This no longer happens with the JUCE port and is one of the main reasons we used JUCE.
