### ISSUE TITLE
XCode should use freshly compiled pforth.dic when compiling hmsl.app

### ISSUE THREAD

**Issue by philburk** [philburk/hmsl#34]
HMSL can be packaged into a .app folder for distribution.
The instructions for how to do that should be added to the README.md file.

**Comment by andrewcsmith** [comment]
I added some instructions, but I'm not really sure what's unclear about the app bundling. If you open the project in xcode, the .app bundle should be the default target. Let me know what's unclear there (or where you're getting stuck) and that might help.

**Comment by philburk** [comment]
My changes to the Forth code were not making it into the .app bundle.
I finally figured out that xcode was grabbing the pforth.dic file from "native/osx/src"! It was not using the pforth.dic that was created by hand in the first build stage.

**Comment by andrewcsmith** [comment]
Ah, good idea. Changing the name of the ticket to reflect the solution.

**Comment by andrewcsmith** [comment]
Scripting a new pforth.dic compilation will require some sort of HMSL version that does not require hitting y/n on startup, or else it hangs forever.

**Comment by andrewcsmith** [comment]
I thought of a better idea—perhaps we just make a version of `save-forth` that saves the dictionary without calling hmsl.init. That way we can have a script that compiles everything, saves `pforth.dic`, and exits. Since SAVE-FORTH is redefined, we can't do that right now.

**Comment by philburk** [comment]
We could modify HMSL.INIT to not ask the user y/n based on some variable. But then that variable would get saved and when HSML was launched it would not ask the user y/n.
An alternative is to put something on the stack as a signal to AUTO.INIT telling it not to recurse. I'll give it a try.

**Comment by andrewcsmith** [comment]
Fixed in #50. I think this is ready to close upon merge.
