### ISSUE TITLE
./HMSL-OSX cannot run SHEP

### ISSUE THREAD

**Issue by philburk** [philburk/hmsl#37]
REPRODUCE:
Build HMSL using the instructions in the README.
cd to the "hmsl" folder.
Enter:  ./HMSL-OSX
Initialize HMSL.
Enter:  SHEP

EXPECT:
SHEP progress bar to be moving and MIDI notes to be sent to SimpleSynth.

ACTUAL:
No progress bar motion. 
Sometimes only a partially drawn editor.
No MIDI output.

ADDITIONAL:
This shows the clock is running:    TIME@ .
But MIDI.SEQOUT does not work.

SHEP works from hmsl.app so it may be an issue with the app environment.

Sometimes this message appears when HMSL.INIT executed.
Do you want to initialize HMSL? (probably Yes)(y/n) 2015-11-10 08:34:13.117 hmsl[20072:1750562] *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

**Comment by andrewcsmith** [comment]
I can't reproduce this one. Does it happen 100% of the time, including with a fresh build running from within XCode?

**Comment by philburk** [comment]
Today it is working differently. MIDI.SEQOUT works.
SHEP only draws partially. See attached.
If I click in SHEP then I can tell that I am changing the shape but the graphics are frozen.
<img width="740" alt="shep_not_drawing" src="https://cloud.githubusercontent.com/assets/5175913/11097175/acf5b2c0-8852-11e5-8e77-259b72b03b43.png">

**Comment by philburk** [comment]
This is using a fresh build. But I was not running from XCode. HMSL can't find the pforth.dic file and I can't find where to set the runtime folder for debugging.

**Comment by philburk** [comment]
Now that hmsl.app can be used, we don't have to fix this. I read that graphics does not work well for command line apps so that explains this. No longer an issue.
