### ISSUE TITLE
version of hmsl.app changes based on folder

### ISSUE THREAD

**Issue by philburk** [philburk/hmsl#38]
REPRODUCE
Build hmsl.app using HMSL version 0.3.4
Right click on hmsl.app on left side of XCode. Select "Show in Finder"
Click once on hmsl.app. It will show "0.3.4" in the sidebar.
Drag hmsl.app to the /hmsl/ folder.
Click once on hmsl.app.

EXPECT
To see version "0.3.4"

ACTUAL
See version "0.3.3"

ADDITIONAL
I know this sounds insane. But it is completely reproducible on my machine.
This makes it hard to know what version is actually being run.

**Comment by andrewcsmith** [comment]
Yep, I can reproduce this as well. I bet it's an OSX problem though.

If you want to know for sure which is being run, you can cd into the hmsl.app folder, open up `Contents/Info.plist` and look at the `CFBundleShortVersionString` element. That doesn't change when you move it from folder to folder. OSX is probably just caching the version somewhere.

If it would help, I could add a line to `host_init` that spits out the version string from Info.plist to the console.

**Comment by philburk** [comment]
I think it would help to display all version that are available. How hard would it be to print it to the HMSL console. PForth already displays its version there.

**Comment by andrewcsmith** [comment]
hmsl.app now prints the version from its Info.plist file.
