### ISSUE TITLE
MIDI Input not working

### ISSUE THREAD

**Issue by philburk** [philburk/hmsl#61]
Or I don't know how to turn it on.

**Comment by andrewcsmith** [comment]
It does work, actually, you just have to explicitly send the midi to HMSL—I turned off the thing that makes HMSL listen on all channels. In Logic Pro X, you just have to select the proper Port from a given General MIDI Device channel.

Let me know if you do that (or have a different program you're using) and it still doesn't work though, cause then we definitely have a problem.

![screenshot 2016-01-07 15 13 33](https://cloud.githubusercontent.com/assets/378677/12185668/54d64a06-b551-11e5-9088-785161fc7d5e.png)

**Comment by philburk** [comment]
I reopened and assigned to me for testing.

**Comment by philburk** [comment]
I verified that MIDI Input was working through Logic by entering MIDI.SCOPE
Thanks.
