### ISSUE TITLE
HMSL should not depend on pforth-xcode

### ISSUE THREAD

**Issue by philburk** [philburk/hmsl#66]
HMSL can be built from the master pForth repo at https://github.com/philburk/pforth

This is important because changes needed for HMSL are going into that repo.
The XCode project could refer to just "pforth" folder instead of "pforth-xcode".
README.md should then be updated.

**Comment by andrewcsmith** [comment]
Would you be opposed to include pforth as a git submodule? That would let people build from source more easily.

**Comment by philburk** [comment]
That sounds like a good idea. Just make sure you use my "pforth" repo and not kristopher's "pforth-xcode".

**Comment by philburk** [comment]
Here are some good instructions for adding a submodule.

https://github.blog/2016-02-01-working-with-submodules/

**Comment by philburk** [comment]
PForth is now a submodule of HMSL.
