### ISSUE TITLE
crash during splorp due to bad free

### ISSUE THREAD

**Issue by philburk** [philburk/hmsl#67]
I was playing Splorp when I got a this crash:

*** error for object 0x84dc00: pointer being freed was not allocated

Thread 2 Crashed:
0   libsystem_kernel.dylib        	0x9d74d58a __pthread_kill + 10
1   libsystem_pthread.dylib       	0x92a98448 pthread_kill + 101
2   libsystem_c.dylib             	0x914b7c34 abort + 156
3   libsystem_malloc.dylib        	0x98ff42ca free + 433
4   com.apple.CoreGraphics        	0x9c9a3627 x_mem_dealloc_size + 91
5   com.apple.CoreGraphics        	0x9c8ee359 CGSDeviceSynchronize + 215
6   libRIP.A.dylib                	0x97271817 ripd_Synchronize + 51
7   libRIP.A.dylib                	0x972715d1 ripc_Operation + 257
8   com.apple.CoreGraphics        	0x9c8ee7c8 CGContextSynchronize + 81
9   hmsl                          	0x00005b4e -[HMSLWindow drawText:atPoint:] + 190 (HMSLWindow.m:95)
10  hmsl                          	0x00004f1b hmslDrawText + 411 (hmsl_cocoa_glue.m:119)
11  hmsl                          	0x000032d2 hostDrawText + 66 (hmsl_gui.c:64)

**Comment by philburk** [comment]
This may be related to issue #64

**Comment by andrewcsmith** [comment]
Fixed by e8b90b594da70c1c17547ceb2ab8d40a83f28bb6
