### ISSUE TITLE
rtc.rate@ used before defined

### ISSUE THREAD

**Issue by andrewcsmith** [philburk/hmsl#69]
This fragment of [global_data.fth](https://github.com/philburk/hmsl/blob/master/hmsl/fth/global_data.fth#L8) uses `rtc.rate@` before it's actually defined. I believe that it should default to the standard `300 / ticks/beat`, and then if [midi_globals.fth](https://github.com/philburk/hmsl/blob/master/hmsl/fth/midi_globals.fth#L38) is used it's possible to override ticks/beat to use the midi clock. Right now, however, it doesn't actually compile.

```
variable TICKS/BEAT
rtc.rate@ 2 * 3 / ticks/beat !
```

**Comment by philburk** [comment]
Moved setting of ticks/beat to time.fth
