### ISSUE TITLE
FLOAT - Deprecated?

### ISSUE THREAD

**Issue by rsnewcomb** [philburk/hmsl#76]
I think I need some remedial instruction on the state of floating point math within firstly HMSL v.4.21 (most of my code was written in v.4.05), but also how/if everything has changed moving to 32-bit Intel.  In my legacy 'Includes' code I also have this, which seems to be problematic, though I have not tried to compile it yet.  Is that actually the cause of the FLOAT error below?  

(I understood that all the H4th includes were now part of the binary executable, but if there are some I need to include explicitly please provide that list.)

>>>
\  	include h4thsystem:FloatingPoint
fpinit
3 places

>>>
\ Utility Words
: int*1000 ( -f- -- decimal , convert float value to decimal * 1000 ) 
	\ ( caller puts float on fp stack )
	1000 float f* int
FLOAT  ? - unrecognized word!
INCLUDE error on line #89 , level = 1 
 1000 float f* int
^^^^^^^^^^^
Stack<10> 
THROW code = -13 
Undefined word!
>>>

**Comment by philburk** [comment]
I need to add aliases for old float words.

: FLOAT S>F ;
: INT F>S ;

**Comment by philburk** [comment]
The float_port.fth file was added to HMSL.
