### ISSUE TITLE
Mapping H4th Include Files to OSX Platform 

### ISSUE THREAD

**Issue by rsnewcomb** [philburk/hmsl#77]
Legacy Migration - this is the set of explicit system include source files I needed to pull in before compiling my own code in order for all my code to function:

\ 	include h4thsystem:debugger
\	include tools:midifile
\ 	include h4thsystem:logto
\	include? 	ob.fader h:ctrl_fader
\ 	include? 	edit.screen ht:screen_editor
\  	include h4thsystem:FloatingPoint
\       include hsys:case
\       include?  ob.xy.controller h:ctrl_xy

I see some of these in the new HMSL folder, others not.

Which ones are *not* compiled into the executable by default?
Which have been replaced/expanded and by which new files?

Thanks.

**Comment by philburk** [comment]
Q&A moved to HMSL mail list forum.
