### ISSUE TITLE
Memory Management in OSX

### ISSUE THREAD

**Issue by rsnewcomb** [philburk/hmsl#78]
Under 68000 - I ran my two systems like so:

'Analysis' -
\	10000000 code-size  	!
\	10000000 headers-size 	!

AND

'Composition' -
\ set code-size 	= 2,000,000
\ set header-size 	= 250,000

In addition, to accommodate very large arrays of dynamic size, I used code to extend physical RAM when needed, and free it when no longer needed:

Code snippet:
		mm.zalloc dword-buffer !
		dword-buffer @ buff !				\ setup ptr
		size dword-buffer-size !			\ save buffer length
cr ." dword-buffer-size = " dword-buffer-size @ .

So, now running HMSL on default RAM allocations on a 10.9.5 system with 4GB RAM, I begin to get allocation errors in compiling object definitions:   **Error in ffCheckDicRoom - no room left in code space**

I will generally be running on my 16GB RAM studio MBP, but this will still be an issue.

What is the default header and code sizing now at play?  Is this somehow related to what Terminal is configured to run with?  (Ugh)  Via Activity Monitor, HMSL appears to be using 4.8MB RAM when code-area error hits. Does HMSL not examine the environment and allocate out memory accordingly?  How do you recommend I manage startup memory and where do I find the code to audit free memory while the code is executing?

This is essential for me to understand, and not having programmed (in any language) in OSX, I realize I may be directed to study OSX memory mgmt from the ground up.  But, any summary explanation within the HMSL context or pragmatic shortcuts you can provide are appreciated.

Thanks,

Robert

**Comment by philburk** [comment]
Enter:    MAP
to see current dictionary sizes.
To resize,

1. launch HMSL
2. don't initialize
3. modify code-size and headers-size
4. c" pforth.dic" save-forth
5. bye

You don't need to study Mac specific memory management.

You generally need more code-size than headers-size

**Comment by rsnewcomb** [comment]
All set for now.
