### ISSUE TITLE
Error building HMSL, 32/64-bit issue

### ISSUE THREAD

**Issue by eval-apply** [philburk/hmsl#81]
I think I've followed the build instructions for OSX correctly and all goes well until `make_hsml.fth`, which fails with the below:

```forth
./HMSL-OSX fth/make_hmsl.fth
PForth V28-LE/64, built Dec 25 2018 06:40:49
pForth loading dictionary from file pforth.dic
     File format version is 10 
     Name space size = 120000 
     Code space size = 300000 
     Entry Point     = 0 
     Cell Size       = 8 
     Little  Endian Dictionary

Including: fth/make_hmsl.fth
Include fth/load_hmsl.fth
' redefined.
Include fth/stubs.fth
    include added 288 bytes,217320 left.
Include fth/p4thbase.fth
RPTR redefined.
BELL redefined.
2018-12-25 06:43:57.913 HMSL-OSX[879:27776] *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]
Declaring fake user variable!
WARNING: DO redefined as ?DO
DO redefined.
? redefined.
    include added BA8 bytes,34430 left.
Include fth/charmacr.fth
TOLOWER redefined.
    include added 560 bytes,213504 left.
Include fth/misc_tools.fth
IN.DICT? redefined.
    include added 3168 bytes,210336 left.
Include fth/utils.fth
IF-DEBUG redefined.
    include added 2464 bytes,207872 left.
Include fth/stacks.fth
s@ - illegal size!
INCLUDE error on line #16 , level = 3 
    ..@ st_depth 1 <
^^^^^^^^^^^^^^^^
INCLUDE error on line #76 , level = 2 
include? stack.header           fth/stacks.fth
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INCLUDE error on line #5 , level = 1 
include fth/load_hmsl.fth
^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by eval-apply** [comment]
Ahh right of course, sadly building a 32-bit binary on OSX is pretty difficult as Xcode no longer supports it.  I guess I could reinstall an older version...

**Comment by eval-apply** [comment]
I remember reading about HMSL (and some other forth based computer music packages like FORMULA etc) a while ago now, but most of my computer music activities are within the lisp family.  Lately for other reasons forth reappeared on the radar and quite by accident I found that HMSL is now open source and was keen to explore.

**Comment by philburk** [comment]
Even though XCode may not support 32-bit binaries, I may be able to make pForth run as a 32-bit Forth by making all addresses simple offsets from the base of an internal memory that is limited in size. PForth can then do all allocations from that base. That may be easier than converting HMSL to work with 64-bit CELLs.

**Comment by eval-apply** [comment]
My Forth skills are limited to the basics, but I'm happy to help test and provide feedback.

**Comment by philburk** [comment]
Thanks. I am about to spend some time on HMSL and could use some help testing. I'll let you know.

**Comment by philburk** [comment]
I ported HMSL to 64-bit while I was porting to JUCE.
One c_struct.fth bug involved cell/ which was defined as

    : cell/  ( n -- n/cell )   2 arshift ;

Doh! I now define it using a conditional.
